# GAME
FPS = 24

# WINDOW DIMENSIONS
WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 768
HALF_WIDTH = int(WINDOW_WIDTH / 2)
HALF_HEIGHT = int(WINDOW_HEIGHT / 2)

 # OBJECTS
SPRITESCALE = 3
FLOORLEVEL = WINDOW_HEIGHT - 180

# IDs
PLAYER = 0
BLOCK = 1



# MECHANICS
GRAVITY = 1.3
WALKING_ACCELERATION = 0.4
RUNNING_ACCELERATION = 0.85
WALKING_THRESHOLD = 9
MAX_SPEED = 19
MAX_FALLING_SPEED = 20
JUMP_VALUE = 23
