# WINDOW DIMENSIONS
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 640

 # OBJECTS
SPRITESCALE = 3
FLOORLEVEL = WINDOW_HEIGHT - 180


# MECHANICS
GRAVITY = 1.5
WALKING_ACCELERATION = 0.5
RUNNING_ACCELERATION = 1.2
WALKING_THRESHOLD = 5
MAX_SPEED = 15
